# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(help_text='You can download up to 5 pictures', upload_to=''),
        ),
    ]
