# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20180611_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_brand',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='cizing',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
